spring.application.name=mall-product
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.namespace=0063f7a1-ed38-4242-94a5-1dc582969923
spring.config.import=nacos:/${spring.application.name}.properties

spring.cache.type=redis
spring.cache.redis.time-to-live=36000000
spring.cache.redis.key-prefix=CACHE_
spring.cache.redis.use-key-prefix=true
#?????????????
spring.cache.redis.cache-null-values=true

mall.thread.core-size=20
mall.thread.max-size=200
mall.thread.keep-alive-time=10
