spring.application.name=mall-gateway
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.config.import=nacos:/${spring.application.name}.properties
spring.cloud.nacos.config.namespace=5baf447c-2288-46a4-8aec-b9cd5197a2b9

server.port=88

