spring.application.name=mall-coupon
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.config.import=nacos:/${spring.application.name}.properties
spring.cloud.nacos.config.namespace=7b0a734a-55db-403b-a9d0-b86e7e630cdb

coupon.user.name=qian
coupon.user.age=18


